### PR TITLE
Add focus style to buttons

### PR DESCRIPTION
**Pull request by denisw**
This improves keyboard accessibility by making the focus state of buttons visible.

### CODE REVIEW

**Comment by sarunast** [comment]
Deploy preview for *masifunde* ready!

Built with commit 70981b18014e574c164982ac8a6edf3c0117401b

https://deploy-preview-132--masifunde.netlify.com

**Comment by torkjels** [comment]
The radio buttons/labels in the donation form doesn't show that they're being focused. We are only applying style to the `label`, and the `radio` within the `label` is what's getting the `focus` event.

**Comment by denisw** [comment]
Oh, I should have said that this is about the `Button` component only, so links looking like buttons.

**Comment by torkjels** [comment]
Ah ok, then! Yeah for the button links this looks good! 👍

**Pull request merged**
