### PR TITLE
Remove "large" Divider type

### PR DESCRIPTION
**Pull request by denisw**
As discussed with Bea, there is only one divider size now.

### CODE REVIEW

**Comment by sarunast** [comment]
Deploy preview for *masifunde* ready!

Built with commit ec2494a94df09a49ff49c756358540f99032bcd5

https://deploy-preview-189--masifunde.netlify.com

**Comment by denisw** [comment]
I searched for all uses of `<Divider />` and the one in the PR is the only one that actually passed a `size`. The others just used the default prop value.

**Comment by sarunast** [comment]
Have looked in `pages` folder for example I find in blog:
`<Divider color="grey" size="large" />` L:82

**Comment by denisw** [comment]
@sarunast, you're right, I somehow missed a few places! Fixed now.

**Pull request merged**
