### PR TITLE
Add feature flag for blog

### PR DESCRIPTION
**Pull request by denisw**
This would allow us to work in a single branch while still being able to release at any time without the blog.

@erikjalevik :trollface:

### CODE REVIEW

**Comment by sarunast** [comment]
Deploy preview for *masifunde* ready!

Built with commit f8ad3562de4f6d09e97b35516c3f936eb0cb8f38

https://deploy-preview-146--masifunde.netlify.com

**Comment by torkjels** [comment]
I don't really have any strong opinion either way for or against feature flags. I've never worked with them before, so it could be a fun (or at least interesting) experience. 🎉

**Comment by torkjels** [comment]
So it seems like this is what we're going for, based on the discussion we had earlier today. What needs to be done to pull the trigger?

**Comment by denisw** [comment]
Changing the `blog` feature flag to `release10` is the only change we need as far as I know.

**Comment by torkjels** [comment]
I meant more along the lines of our workflow. After we accept this, should we also just merge `release-1.0` into master and get rid of long lived branches right away?

**Comment by denisw** [comment]
Yes. Otherwise we have doubled the complexity.

**Pull request merged**
