### PR TITLE
Add Futurice logos to footer

### PR DESCRIPTION
**Pull request by denisw**
The visual size of the "Built by Futurice" and "Powered by Contentful" logos don't quite match when giving the images the same height, so I had to add a little padding to the Contentful logo image.

### CODE REVIEW

**Comment by sarunast** [comment]
Deploy preview for *masifunde* ready!

Built with commit 97d3641117f5ec3394a794b81698adf3507cb382

https://deploy-preview-129--masifunde.netlify.com

**Comment by denisw** [comment]
I did indeed forget the images. 😅 Added them now. Also, good catch with the logo order! Fixed.

**Comment by torkjels** [comment]
Hehe, good! 👍 
I think it's worth it to add a bit more spacing above and below the icons, just like in the designs. The designs also has a tiny bit more side spacing between the icons, but I don't think that's the most important.
But some more spacing above and below would make it feel a bit less crammed 👍

**Comment by denisw** [comment]
I increased the spacing above/below the logos a bit @torkjels.

**Pull request merged**
