### PR TITLE
Add Transparenz page

### PR DESCRIPTION
**Pull request by erikjalevik**

### CODE REVIEW

**Comment by sarunast** [comment]
Deploy preview for *masifunde* ready!

Built with commit 6af0e1c727fd588480e6cc40e9767111b488acd1

https://deploy-preview-224--masifunde.netlify.com

**Comment by denisw** [comment]
I cannot access `/transparenz` in the deploy preview, nor do I see a link to it in the footer.

**Comment by denisw** [comment]
No lack with a static local export as well. Only accessible through the server (`npm run dev`).

**Comment by denisw** [comment]
Oh sorry, I didn't build with the `release10` feature flag on. Now the local static export has the Transparenz page. But I still don't see it linked to from anywhere.

**Pull request merged**
